### ISSUE TITLE
Add transparent option to images

### ISSUE THREAD

**Issue by ianyimi** [spacesvr/spacesvr#43]
Allow for png images to be shown without a background on the image component

**Comment by AlaricBaraou** [comment]
I can enable image transparency for .png by setting transparent to true on the image material. 
But when used with a frame, it will use the color of the frame as a background.

Do we need the inside of the frame to be transparent when used with a png ?
If yes, the frame component will need some adjustments otherwise it's just about the transparent property on the image material.

Also if I understood correctly, it's up to the user to enable this transparency or not right ? 
Or are we going with a default transparent material when a .png is used ?

I see pro and cons to both approch.

I'll do a PR when I'll have those infos :)

**Comment by ianyimi** [comment]
Thanks for this note I forgot about the frame back. Transparency doesn't need to be the default setting. I think it would be nice to have the inside of the frame be transparent as well and it shouldn't be too difficult a fix either. Also yes, the user will be able to toggle transparency.

**Comment by ianyimi** [comment]
Also I just thought of this but it would be cool as well to add a frameColor attribute to the image component, but I'll make a new issue for this
